# Generated by Django 5.0.6 on 2024-05-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('request_count', models.IntegerField(default=0)),
                ('last_request', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
